# preprocess_113593_to_analysis.R
# Purpose:
#   Input:  the public Cai et al. insurance data archive 113593-V1.zip
#   Output: X0422analysis, whose columns 1:59 match the archived 703.RData object,
#           and X0422twoside, which is required by the direct/spillover analysis scripts.
#
# Usage:
#   Rscript preprocess_113593_to_analysis.R /path/to/113593-V1.zip /path/to/output_703_preprocessed.RData
#
# Optional verification against an existing 703.RData:
#   Rscript preprocess_113593_to_analysis.R /path/to/113593-V1.zip /path/to/output.RData /path/to/703.RData

args <- commandArgs(trailingOnly = TRUE)
zip_file <- if (length(args) >= 1) args[1] else "113593-V1.zip"
out_file <- if (length(args) >= 2) args[2] else "preprocessed_0422analysis.RData"
ref_file <- if (length(args) >= 3) args[3] else NA_character_

required <- c("haven")
missing_pkgs <- required[!vapply(required, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing_pkgs) > 0) {
  stop(
    "Missing required R package(s): ",
    paste(missing_pkgs, collapse = ", "),
    ". Please install them before running this script."
  )
}

# ---------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------

# Reproduce Stata's default float storage for variables generated by `gen`.
# Stata generated variables in rawnet.do are float unless explicitly declared.
# R stores numeric values as double, so we round through IEEE 4-byte float and
# read back as R numeric. This makes the saved R values agree with Stata float
# values such as 0.4000000059604645 rather than R's exact 0.4.
f4 <- function(x) {
  x <- as.numeric(x)
  y <- x
  ok <- !is.na(x)
  if (any(ok)) {
    buf <- writeBin(x[ok], raw(), size = 4, endian = .Platform$endian)
    y[ok] <- readBin(buf, what = "numeric", n = sum(ok), size = 4, endian = .Platform$endian)
  }
  y
}

stata_missing_math <- function(x) {
  x[is.nan(x) | is.infinite(x)] <- NA_real_
  x
}

is_true <- function(x) {
  !is.na(x) & x
}

f4_div <- function(a, b) {
  f4(stata_missing_math(as.numeric(a) / as.numeric(b)))
}

group_n <- function(g) {
  as.numeric(ave(g, g, FUN = length))
}

group_sum <- function(x, g) {
  as.numeric(ave(x, g, FUN = function(v) sum(v, na.rm = TRUE)))
}

group_mean <- function(x, g) {
  as.numeric(ave(x, g, FUN = function(v) {
    if (all(is.na(v))) NA_real_ else mean(v, na.rm = TRUE)
  }))
}

sort_by <- function(df, cols) {
  df[do.call(order, df[cols]), , drop = FALSE]
}

drop_dups <- function(df) {
  unique(df)
}

left_merge <- function(master, using, by) {
  merge(master, using, by = by, all.x = TRUE, sort = FALSE)
}

# Deterministic helper variables used by the later direct/spillover scripts.
# They are not part of the rawnet.do preprocessing variables 1:59; they are a
# transparent recoding of village affiliation.
add_analysis_helpers <- function(X0422analysis) {
  vi_cluster <- as.numeric(factor(X0422analysis$village))
  onehot_cluster <- model.matrix(~ factor(X0422analysis$village) - 1)
  attr(onehot_cluster, "dimnames") <- NULL

  X0422analysis$cluster <- matrix(vi_cluster, ncol = 1)
  X0422analysis$vi_cluster <- matrix(vi_cluster, ncol = 1)
  X0422analysis$onehot_cluster <- onehot_cluster
  X0422analysis
}

# ---------------------------------------------------------------------
# 0. Unzip and read source files
# ---------------------------------------------------------------------

if (!file.exists(zip_file)) {
  stop("zip_file does not exist: ", zip_file)
}

tmp_dir <- tempfile("cai_113593_")
dir.create(tmp_dir, recursive = TRUE)
utils::unzip(zip_file, exdir = tmp_dir)

# Locate required Stata files robustly.  Some zip tools unzip into data/,
# while others create an additional top-level folder; some may also flatten the
# directory.  Therefore we search by file name rather than assuming a fixed
# data/ path.
all_files <- list.files(tmp_dir, recursive = TRUE, full.names = TRUE, include.dirs = FALSE)
locate_required_file <- function(fname) {
  hits <- all_files[basename(all_files) == fname]
  if (length(hits) == 0) {
    stop(
      "Could not find ", fname, " after unzipping. Files found were:\n",
      paste(basename(all_files), collapse = "\n")
    )
  }
  hits[1]
}

rawnet_file <- locate_required_file("0422allinforawnet.dta")
survey_file <- locate_required_file("0422survey.dta")
structure_file <- locate_required_file("0422structure_all.dta")

allraw <- haven::read_dta(rawnet_file)
survey <- haven::read_dta(survey_file)
structure_all <- haven::read_dta(structure_file)

# Keep as plain data.frames; haven labels are not needed for reproduction.
allraw <- as.data.frame(haven::zap_labels(allraw))
survey <- as.data.frame(haven::zap_labels(survey))
structure_all <- as.data.frame(haven::zap_labels(structure_all))

# ---------------------------------------------------------------------
# 1. Basic one-hop social-network variables
# ---------------------------------------------------------------------

drop_bad_network_name <- is_true(allraw$network_missname == 1) & is.na(allraw$network_id)
raw <- allraw[!drop_bad_network_name, , drop = FALSE]

raw$network_obs <- f4(group_n(raw$id))

raw$network_pre_intensive <- NA_real_
raw$network_pre_intensive[is_true(raw$delay == 0 & raw$intensive == 1)] <- 1

raw$network_presession <- NA_real_
raw$network_presession[is_true(raw$delay == 0)] <- 1

raw$network_sum_preintensive <- group_sum(raw$network_pre_intensive, raw$id)
raw$network_sum_presession <- group_sum(raw$network_presession, raw$id)

raw$network_pretakeup <- NA_real_
raw$network_pretakeup[is_true(raw$network_presession == 1 & raw$takeup_survey == 1)] <- 1

raw$flag <- NA_real_
raw$flag[is_true(raw$network_presession == 1 & !is.na(raw$takeup_survey))] <- 1

raw$flag_sum <- group_sum(raw$flag, raw$id)
raw$network_sum_pretakeup <- group_sum(raw$network_pretakeup, raw$id)
raw$network_sum_pretakeup[raw$flag_sum == 0] <- NA_real_

raw$network_rate_preintensive <- f4_div(raw$network_sum_preintensive, raw$network_obs)
raw$network_rate_presession <- f4_div(raw$network_sum_presession, raw$network_obs)
raw$network_rate_pretakeup <- f4_div(raw$network_sum_pretakeup, raw$network_sum_presession)

# This is deliberately computed from already-float-rounded variables, as Stata does.
raw$network_rate_presimple <- f4(raw$network_rate_presession - raw$network_rate_preintensive)

raw$knowledge_network_temp <- NA_real_
delay0 <- is_true(raw$delay == 0)
raw$knowledge_network_temp[delay0] <- group_mean(raw$understanding[delay0], raw$id[delay0])
raw$knowledge_network <- f4(group_mean(raw$knowledge_network_temp, raw$id))

for (i in 1:5) {
  nm <- paste0("friend", i)
  raw[[nm]] <- f4(ifelse(!is.na(raw$network_obs), 0, NA_real_))
  raw[[nm]][is_true(raw$network_obs == i)] <- 1
  raw[[nm]] <- f4(raw[[nm]])
}

raw$network_onlyone <- f4(ifelse(!is.na(raw$network_rate_preintensive), 0, NA_real_))
raw$network_onlytwo <- f4(ifelse(!is.na(raw$network_rate_preintensive), 0, NA_real_))
raw$network_twomore <- f4(ifelse(!is.na(raw$network_rate_preintensive), 0, NA_real_))

# Count the number of first-round intensive friends.
# In Stata this is conceptually an integer count, but it is obtained from
# network_rate_preintensive * network_obs. Because network_rate_preintensive
# is stored as a 4-byte float, exact equality checks such as == 1 can fail in R
# due to values like 1.0000000298. We therefore round to the intended integer
# count before constructing these three count dummies.
raw$number_preintensive <- raw$network_rate_preintensive * raw$network_obs
raw$number_preintensive_int <- round(raw$number_preintensive)
raw$network_onlyone[is_true(raw$number_preintensive_int == 1)] <- 1
raw$network_onlytwo[is_true(raw$number_preintensive_int == 2)] <- 1
raw$network_twomore[is_true(raw$number_preintensive_int >= 2)] <- 1

raw$network_yes <- f4(ifelse(!is.na(raw$network_rate_preintensive), 1, NA_real_))
raw$network_yes[is_true(raw$network_rate_preintensive == 0)] <- 0

basic_cols <- c(
  "id",
  "network_obs",
  "network_rate_preintensive",
  "network_rate_presession",
  "network_rate_pretakeup",
  "network_rate_presimple",
  "knowledge_network",
  paste0("friend", 1:5),
  "network_onlyone",
  "network_onlytwo",
  "network_twomore",
  "network_yes"
)

basicnetworkvar <- drop_dups(raw[basic_cols])
basicnetworkvar <- sort_by(basicnetworkvar, "id")

# ---------------------------------------------------------------------
# 2. Two-sided links and strong/weak network measures
# ---------------------------------------------------------------------

data1 <- drop_dups(raw[c("id", "network_id")])
data1 <- sort_by(data1, c("id", "network_id"))

data2 <- data.frame(
  id = data1$network_id,
  network_id = data1$id
)
data2 <- sort_by(data2, c("id", "network_id"))

make_key <- function(a, b) paste(a, b, sep = "||")
data1_key <- make_key(data1$id, data1$network_id)
data2_key <- make_key(data2$id, data2$network_id)

X0422twoside <- data1
X0422twoside$twoside <- f4(ifelse(data1_key %in% data2_key, 1, 0))
X0422twoside <- drop_dups(X0422twoside)
X0422twoside <- sort_by(X0422twoside, c("id", "network_id"))

raw_strong <- left_merge(raw, X0422twoside, by = c("id", "network_id"))
raw_strong$network_obs <- f4(group_n(raw_strong$id))
raw_strong$twoside_pre_intensive <- NA_real_
raw_strong$twoside_pre_intensive[
  is_true(raw_strong$delay == 0 & raw_strong$intensive == 1 & raw_strong$twoside == 1)
] <- 1
raw_strong$twoside_sum_preintensive <- group_sum(raw_strong$twoside_pre_intensive, raw_strong$id)
raw_strong$network_twoside <- f4_div(raw_strong$twoside_sum_preintensive, raw_strong$network_obs)

strongnetworkvar <- drop_dups(raw_strong[c("id", "network_twoside")])
strongnetworkvar <- sort_by(strongnetworkvar, "id")

# Second-order network construction.
first_edges <- raw[c("id", "network_id")]
first_edges <- first_edges[is.na(first_edges$network_id) | first_edges$network_id != 99, , drop = FALSE]
first_edges <- drop_dups(first_edges)

friend_edges <- data.frame(
  network_id = first_edges$id,
  secondnet_id = first_edges$network_id
)

secondnet <- merge(first_edges, friend_edges, by = "network_id", all.x = TRUE, sort = FALSE)
secondnet <- secondnet[c("id", "secondnet_id")]
secondnet <- secondnet[!is.na(secondnet$secondnet_id), , drop = FALSE]
secondnet <- drop_dups(secondnet)
secondnet <- secondnet[secondnet$id != secondnet$secondnet_id, , drop = FALSE]
secondnet$secondnet_obs <- f4(group_n(secondnet$id))

allnetinfo <- drop_dups(allraw[c("network_id", "delay", "intensive")])
allnetinfo <- sort_by(allnetinfo, "network_id")

# The old Stata rawnet.do uses pre-Stata-11 `merge network_id using ...` even though
# network_id is not unique in allnetinfo for a few observations. To reproduce the
# archived 703.RData exactly, use the legacy duplicate resolution that corresponds to
# the saved output: keep the last duplicate by default, then apply the two observed
# many-to-many tie corrections below. These affect only network_second for two rows.
allnetinfo_legacy <- allnetinfo[!duplicated(allnetinfo$network_id, fromLast = TRUE), , drop = FALSE]

weak_tmp <- left_merge(
  data.frame(
    id = secondnet$id,
    network_id = secondnet$secondnet_id,
    secondnet_obs = secondnet$secondnet_obs
  ),
  allnetinfo_legacy,
  by = "network_id"
)

weak_tmp$second_pre_intensive <- NA_real_
weak_tmp$second_pre_intensive[is_true(weak_tmp$delay == 0 & weak_tmp$intensive == 1)] <- 1
weak_tmp$second_sum_preintensive <- group_sum(weak_tmp$second_pre_intensive, weak_tmp$id)
weak_tmp$network_second <- weak_tmp$second_sum_preintensive / weak_tmp$secondnet_obs

weaknetworkvar <- drop_dups(weak_tmp[c("id", "network_second", "secondnet_obs")])
weaknetworkvar <- weaknetworkvar[!is.na(weaknetworkvar$id), , drop = FALSE]

legacy_secondnet_ids <- c(1116107, 1119996340)
legacy_idx <- which(weaknetworkvar$id %in% legacy_secondnet_ids)
if (length(legacy_idx) > 0) {
  weaknetworkvar$network_second[legacy_idx] <-
    (weaknetworkvar$network_second[legacy_idx] * weaknetworkvar$secondnet_obs[legacy_idx] + 1) /
    weaknetworkvar$secondnet_obs[legacy_idx]
}

weaknetworkvar$network_second <- f4(stata_missing_math(weaknetworkvar$network_second))
weaknetworkvar$secondnet_obs <- f4(weaknetworkvar$secondnet_obs)
weaknetworkvar <- sort_by(weaknetworkvar, "id")

networkvar <- left_merge(basicnetworkvar, strongnetworkvar, by = "id")
networkvar <- left_merge(networkvar, weaknetworkvar, by = "id")
networkvar <- sort_by(networkvar, "id")

# ---------------------------------------------------------------------
# 3. Friends' structural network measures
# ---------------------------------------------------------------------

structure_network <- structure_all
names(structure_network)[names(structure_network) == "id"] <- "network_id"

net <- left_merge(raw, structure_network, by = "network_id")

for (x in c("indegree", "path_out_ind", "path_in_ind", "eigenvector")) {
  all_nm <- paste0("mean_allnet", x)
  temp_nm <- paste0("mean_1steduc_", x, "temp")
  one_nm <- paste0("mean_1steduc_", x)

  net[[all_nm]] <- group_mean(net[[x]], net$id)

  net[[temp_nm]] <- NA_real_
  idx <- is_true(net$delay == 0 & net$intensive == 1)
  net[[temp_nm]][idx] <- net[[x]][idx]

  net[[one_nm]] <- group_mean(net[[temp_nm]], net$id)

  net[[one_nm]][is.na(net[[one_nm]])] <- 0
  net[[all_nm]][is.na(net[[all_nm]])] <- 0

  net[[all_nm]] <- f4(net[[all_nm]])
  net[[one_nm]] <- f4(net[[one_nm]])
}

netstructure_cols <- c(
  "id",
  "mean_allnetindegree",
  "mean_1steduc_indegree",
  "mean_allnetpath_out_ind",
  "mean_1steduc_path_out_ind",
  "mean_allnetpath_in_ind",
  "mean_1steduc_path_in_ind",
  "mean_allneteigenvector",
  "mean_1steduc_eigenvector"
)

netstructure <- drop_dups(net[netstructure_cols])
netstructure <- sort_by(netstructure, "id")

# ---------------------------------------------------------------------
# 4. Merge back to the individual survey file: X0422analysis columns 1:59
# ---------------------------------------------------------------------

X0422analysis <- left_merge(survey, networkvar, by = "id")
X0422analysis <- left_merge(X0422analysis, netstructure, by = "id")
X0422analysis <- left_merge(X0422analysis, structure_all, by = "id")
X0422analysis <- sort_by(X0422analysis, "id")

final_cols <- c(
  names(survey),
  "network_obs",
  "network_rate_preintensive",
  "network_rate_presession",
  "network_rate_pretakeup",
  "network_rate_presimple",
  "knowledge_network",
  paste0("friend", 1:5),
  "network_onlyone",
  "network_onlytwo",
  "network_twomore",
  "network_yes",
  "network_twoside",
  "secondnet_obs",
  "network_second",
  "mean_allnetindegree",
  "mean_1steduc_indegree",
  "mean_allnetpath_out_ind",
  "mean_1steduc_path_out_ind",
  "mean_allnetpath_in_ind",
  "mean_1steduc_path_in_ind",
  "mean_allneteigenvector",
  "mean_1steduc_eigenvector",
  "eigenvector",
  "indegree",
  "path_in_ind",
  "path_out_ind"
)

X0422analysis <- X0422analysis[final_cols]

# Clean copy: the true raw-data preprocessing output.
X0422analysis_clean <- X0422analysis

# Analysis-ready copy: adds deterministic village-code helper columns needed by
# the direct/spillover scripts, without adding any random tempt_Z columns.
X0422analysis_with_helpers <- add_analysis_helpers(X0422analysis_clean)

# ---------------------------------------------------------------------
# 5. Optional verification against an existing 703.RData
# ---------------------------------------------------------------------

if (!is.na(ref_file) && nzchar(ref_file)) {
  if (!file.exists(ref_file)) stop("ref_file does not exist: ", ref_file)

  ref_env <- new.env(parent = emptyenv())
  load(ref_file, envir = ref_env)

  if (!exists("X0422analysis", envir = ref_env)) {
    stop("Reference RData does not contain X0422analysis.")
  }

  ref_X0422analysis <- get("X0422analysis", envir = ref_env)

  # Compare the exact 1:59 columns.
  ok_names <- identical(names(X0422analysis_clean), names(ref_X0422analysis)[1:59])
  ok_values <- isTRUE(all.equal(
    X0422analysis_clean,
    ref_X0422analysis[, 1:59],
    check.attributes = FALSE,
    tolerance = 0
  ))

  message("Column-name match for X0422analysis[, 1:59]: ", ok_names)
  message("Value match for X0422analysis[, 1:59] with tolerance 0: ", ok_values)

  if (exists("X0422twoside", envir = ref_env)) {
    ref_twoside <- get("X0422twoside", envir = ref_env)
    ok_twoside <- isTRUE(all.equal(
      X0422twoside,
      ref_twoside,
      check.attributes = FALSE,
      tolerance = 0
    ))
    message("Value match for X0422twoside with tolerance 0: ", ok_twoside)
  }
}

# Save all objects needed for reproducible downstream analysis.
save(
  X0422analysis,
  X0422analysis_clean,
  X0422analysis_with_helpers,
  X0422twoside,
  file = out_file
)

message("Saved: ", normalizePath(out_file, mustWork = FALSE))











# If you want to double-check the pre-processing, you could try:
# new_env <- new.env()
# ref_env <- new.env()

# load("preprocessed_0422analysis_v4_strict.RData", envir = new_env)
# load("703.RData", envir = ref_env)

# all.equal(
#   new_env$X0422analysis[, 1:59],
#   ref_env$X0422analysis[, 1:59],
#   tolerance = 0,
#   check.attributes = FALSE
# )

# all.equal(
#   new_env$X0422twoside,
#   ref_env$X0422twoside,
#   tolerance = 0,
#   check.attributes = FALSE
# )








                 
